/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface CodecartelSideDrawer {
    'headerTitle': string;
  }
  interface CodecartelSideDrawerAttributes extends StencilHTMLAttributes {
    'headerTitle'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'CodecartelSideDrawer': Components.CodecartelSideDrawer;
  }

  interface StencilIntrinsicElements {
    'codecartel-side-drawer': Components.CodecartelSideDrawerAttributes;
  }


  interface HTMLCodecartelSideDrawerElement extends Components.CodecartelSideDrawer, HTMLStencilElement {}
  var HTMLCodecartelSideDrawerElement: {
    prototype: HTMLCodecartelSideDrawerElement;
    new (): HTMLCodecartelSideDrawerElement;
  };

  interface HTMLElementTagNameMap {
    'codecartel-side-drawer': HTMLCodecartelSideDrawerElement
  }

  interface ElementTagNameMap {
    'codecartel-side-drawer': HTMLCodecartelSideDrawerElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
