/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface CodecartelSideDrawer {
    'headerTitle': string;
    'isOpen': boolean;
    'open': () => void;
  }
  interface CodecartelSideDrawerAttributes extends StencilHTMLAttributes {
    'headerTitle'?: string;
    'isOpen'?: boolean;
  }

  interface CodecartelStockPrice {}
  interface CodecartelStockPriceAttributes extends StencilHTMLAttributes {}

  interface CodecartelTooltip {
    'isHidden': boolean;
    'tooltipText': string;
  }
  interface CodecartelTooltipAttributes extends StencilHTMLAttributes {
    'isHidden'?: boolean;
    'tooltipText'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'CodecartelSideDrawer': Components.CodecartelSideDrawer;
    'CodecartelStockPrice': Components.CodecartelStockPrice;
    'CodecartelTooltip': Components.CodecartelTooltip;
  }

  interface StencilIntrinsicElements {
    'codecartel-side-drawer': Components.CodecartelSideDrawerAttributes;
    'codecartel-stock-price': Components.CodecartelStockPriceAttributes;
    'codecartel-tooltip': Components.CodecartelTooltipAttributes;
  }


  interface HTMLCodecartelSideDrawerElement extends Components.CodecartelSideDrawer, HTMLStencilElement {}
  var HTMLCodecartelSideDrawerElement: {
    prototype: HTMLCodecartelSideDrawerElement;
    new (): HTMLCodecartelSideDrawerElement;
  };

  interface HTMLCodecartelStockPriceElement extends Components.CodecartelStockPrice, HTMLStencilElement {}
  var HTMLCodecartelStockPriceElement: {
    prototype: HTMLCodecartelStockPriceElement;
    new (): HTMLCodecartelStockPriceElement;
  };

  interface HTMLCodecartelTooltipElement extends Components.CodecartelTooltip, HTMLStencilElement {}
  var HTMLCodecartelTooltipElement: {
    prototype: HTMLCodecartelTooltipElement;
    new (): HTMLCodecartelTooltipElement;
  };

  interface HTMLElementTagNameMap {
    'codecartel-side-drawer': HTMLCodecartelSideDrawerElement
    'codecartel-stock-price': HTMLCodecartelStockPriceElement
    'codecartel-tooltip': HTMLCodecartelTooltipElement
  }

  interface ElementTagNameMap {
    'codecartel-side-drawer': HTMLCodecartelSideDrawerElement;
    'codecartel-stock-price': HTMLCodecartelStockPriceElement;
    'codecartel-tooltip': HTMLCodecartelTooltipElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
