/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface CodecartelSideDrawer {
    'headerTitle': string;
    'isOpen': boolean;
    'open': () => void;
  }
  interface CodecartelSideDrawerAttributes extends StencilHTMLAttributes {
    'headerTitle'?: string;
    'isOpen'?: boolean;
  }

  interface CodecartelTooltip {}
  interface CodecartelTooltipAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'CodecartelSideDrawer': Components.CodecartelSideDrawer;
    'CodecartelTooltip': Components.CodecartelTooltip;
  }

  interface StencilIntrinsicElements {
    'codecartel-side-drawer': Components.CodecartelSideDrawerAttributes;
    'codecartel-tooltip': Components.CodecartelTooltipAttributes;
  }


  interface HTMLCodecartelSideDrawerElement extends Components.CodecartelSideDrawer, HTMLStencilElement {}
  var HTMLCodecartelSideDrawerElement: {
    prototype: HTMLCodecartelSideDrawerElement;
    new (): HTMLCodecartelSideDrawerElement;
  };

  interface HTMLCodecartelTooltipElement extends Components.CodecartelTooltip, HTMLStencilElement {}
  var HTMLCodecartelTooltipElement: {
    prototype: HTMLCodecartelTooltipElement;
    new (): HTMLCodecartelTooltipElement;
  };

  interface HTMLElementTagNameMap {
    'codecartel-side-drawer': HTMLCodecartelSideDrawerElement
    'codecartel-tooltip': HTMLCodecartelTooltipElement
  }

  interface ElementTagNameMap {
    'codecartel-side-drawer': HTMLCodecartelSideDrawerElement;
    'codecartel-tooltip': HTMLCodecartelTooltipElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
